-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-09-02T13:06:43.796Z
--<DBT_CODE>

WITH raw_listings AS ( SELECT * FROM {{ source('raw_listings', 'raw_listings') }})

select * from raw_listings limit 007
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from raw_listings limit 007
--</ORIGINAL_CODE>