-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-09-17T09:46:30.096Z
--<DBT_CODE>

WITH ecom__raw_customers AS ( SELECT * FROM {{ source('ecom', 'raw_customers') }})

select * from ecom__raw_customers
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from ecom__raw_customers;
--</ORIGINAL_CODE>