-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-09-30T12:40:26.153Z
--<DBT_CODE>

WITH ecom__raw_customers AS ( SELECT * FROM {{ source('ecom', 'raw_customers') }})

select id from ecom__raw_customers
--</DBT_CODE>
--<ORIGINAL_CODE>
--select id from ecom__raw_customers;
--</ORIGINAL_CODE>