-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-10-21T07:12:43.012Z
--<DBT_CODE>

WITH test55 AS (SELECT * FROM {{ ref('test55') }})

select * from test55
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from test55;
--</ORIGINAL_CODE>