-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-09-02T13:50:32.721Z
--<DBT_CODE>

WITH raw_listings AS ( SELECT * FROM {{ source('raw_listings', 'raw_listings') }})

select * from raw_listings limit 91
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from raw_listings limit 91;
--</ORIGINAL_CODE>