-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-09-14T13:37:11.629Z
--<DBT_CODE>

WITH raw_reviews AS ( SELECT * FROM {{ source('raw_reviews', 'raw_reviews') }})

select * from raw_reviews
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from raw_reviews;
--</ORIGINAL_CODE>