-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-10-21T07:18:57.631Z
--<DBT_CODE>

WITH test_3 AS (SELECT * FROM {{ ref('test_3') }})

select * from test_3
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from test_3;
--</ORIGINAL_CODE>