-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-08-03T12:01:46.615Z
--<DBT_CODE>

WITH raw_listings AS ( SELECT * FROM {{ source('raw_listings', 'raw_listings') }})

select * from raw_listings
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from raw_listings;
--</ORIGINAL_CODE>