-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-10-15T12:29:43.392Z
--<DBT_CODE>

WITH raw_listings AS ( SELECT * FROM {{ source('raw_listings', 'raw_listings') }})

select * from raw_listings limit 2
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from raw_listings limit 2;
--</ORIGINAL_CODE>