-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-10-06T11:23:08.220Z
--<DBT_CODE>

WITH raw_listings AS ( SELECT * FROM {{ source('raw_listings', 'raw_listings') }})

select * from raw_listings
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from raw_listings;
--</ORIGINAL_CODE>