-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-08-06T12:00:33.958Z
--<DBT_CODE>

WITH raw_listings AS ( SELECT * FROM {{ source('raw_listings', 'raw_listings') }})

select
id as ID,
created_at as CREATED_AT
from
raw_listings
limit
11
order by created_at desc
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  id as ID,
--  created_at as CREATED_AT
--from
--  raw_listings
--limit
--  11
--order by created_at desc;
--</ORIGINAL_CODE>