-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-09-02T11:19:14.939Z
--<DBT_CODE>

WITH raw_listings AS ( SELECT * FROM {{ source('raw_listings', 'raw_listings') }})

select
id as ID,
created_at as CREATED_AT
from
raw_listings
limit
12
order by created_at desc
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  id as ID,
--  created_at as CREATED_AT
--from
--  raw_listings
--limit
--  12
--order by created_at desc;
--</ORIGINAL_CODE>