-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-08-19T12:41:49.811Z
--<DBT_CODE>

WITH CONTACTS AS ( SELECT * FROM {{ source('CONTACTS', 'CONTACTS') }})

select
id as ID,
created_at as CREATED_AT
from
contacts
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  id as ID,
--  created_at as CREATED_AT
--from
--  contacts;
--</ORIGINAL_CODE>