-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-08-05T13:59:56.832Z
--<DBT_CODE>

WITH raw_listings AS ( SELECT * FROM {{ source('raw_listings', 'raw_listings') }})

select
h.id,
h.name,
h.host_id,
h.updated_at as updated,
h.created_at as created
from
raw_listings h
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  h.id,
--  h.name,
--  h.host_id,
--  h.updated_at as updated,
--  h.created_at as created
--from
--  raw_listings h
--</ORIGINAL_CODE>