-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-08-06T09:00:43.153Z
--<DBT_CODE>

WITH raw_listings AS ( SELECT * FROM {{ source('raw_listings', 'raw_listings') }})

select
id
from
raw_listings h
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  id
--from
--  raw_listings h
--</ORIGINAL_CODE>