-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-08-24T12:58:47.982Z
--<DBT_CODE>

WITH CONTACTS AS ( SELECT * FROM {{ source('CONTACTS', 'CONTACTS') }})

select
*
from
contacts
limit
444
--</DBT_CODE>
--<ORIGINAL_CODE>
--select
--  *
--from
--  contacts
--limit
--  444;
--</ORIGINAL_CODE>