-- AUTO GENERATED BY MONTARA
--UPDATED: 2025-10-21T11:43:00.904Z
--<DBT_CODE>

WITH ecom__raw_customers AS ( SELECT * FROM {{ source('ecom', 'raw_customers') }})

select * from ecom__raw_customers limit 300
--</DBT_CODE>
--<ORIGINAL_CODE>
--select * from ecom__raw_customers limit 300;
--</ORIGINAL_CODE>